#!/bin/bash
dpkg-deb --build sahkomittari/client/src deb/konttiraspi-sahkomittari-client.deb
dpkg-deb --build sahkomittari/server/src deb/konttiraspi-sahkomittari-server.deb
dpkg-deb --build mesh/client/src deb/konttiraspi-mesh-client.deb
dpkg-deb --build mesh/gateway/src deb/konttiraspi-mesh-gateway.deb
dpkg-deb --build system/src deb/konttiraspi-system.deb
