#!/bin/bash
. /boot/asetukset.txt

if [[ $1 == "up" ]]; then
    if (lsmod|grep batman_adv) >/dev/null;then
        echo "On jo käynnissä!"
        exit 1
    fi
    #sudo iw reg get
    #sudo iw reg set US
    # sudo iw wlan1 set txpower fixed 3000

    echo "Käynnistetään mesh-gateway taajuudelle $mesh_mhz Mhz käyttäen laitetta $mesh_device"
    #sudo modprobe -r 88XXau && sudo modprobe 88XXau rtw_vht_enable=2
    sudo modprobe batman-adv 2>/dev/null
    sudo killall wpa_supplicant 2>/dev/null
    sudo sysctl -w net.ipv4.ip_forward=1 >/dev/null
    sudo ip link set $mesh_device down
    sudo iw reg set $mesh_country
    sudo  iwconfig wlan1 txpower $mesh_txpower
    #sudo iw $laite set txpower fixed 3000
    sudo ip link set mtu $mesh_mtu dev $mesh_device
    sleep 1
    sudo iw $mesh_device set type ibss
    sudo ip link set $mesh_device up
    sleep 2
    sudo iw $mesh_device ibss join mesh $mesh_mhz NOHT #[NOHT|HT20|HT40+|HT40-|5MHz|10MHz|80MHz]
    sudo batctl ra BATMAN_V
    #sudo batctl ra BATMAN_IV
    sudo batctl if add $mesh_device
    sudo ip link set bat0 up
    sudo batctl gw_mode server
    sudo ip -6 addr add fe80::ba27:ebff:fe77:3d38/64 dev bat0 #wwww https://github.com/suiluj/pi-adhoc-mqtt-cluster/wiki/Batman-Adv-and-Batctl#option-3-batman-meshnode-with-internet-gateway
    sudo ip addr add $mesh_ip/24 broadcast $mesh_broadcast dev bat0
    #sleep 1
    sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    sudo iptables -A FORWARD -i eth0 -o bat0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    sudo iptables -A FORWARD -i bat0 -o eth0 -j ACCEPT
    echo "Valmis"

    ##sleep 10 #wwww -->
    ##sudo alfred -i bat0 -m -p 1 &
    ##sleep 10
    ##sudo batadv-vis -i bat0 -s &
elif [[ $1 == "down" ]];then
    if !(lsmod|grep batman_adv) >/dev/null;then
        echo "Ei ole käynnissä!"
        exit 1
    fi
    sudo ip link set $mesh_device down
    sudo ip addr flush dev $mesh_device
    sudo iw $mesh_device set type managed
    sudo rmmod batman-adv
    sudo ip link set mtu $mesh_mtu dev $mesh_device
    #sudo ip link del mesh-bridge
    sudo iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    sudo iptables -D FORWARD -i eth0 -o bat0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    sudo iptables -D FORWARD -i bat0 -o eth0 -j ACCEPT
else
    echo "käyttö:"
    echo "$0 {up|down}"
fi
