#!/bin/bash
. /boot/asetukset.txt
if [[ $1 == "up" ]]; then
    if (lsmod|grep batman_adv) >/dev/null;then
        echo "On jo käynnissä!"
        exit 1
    fi
     echo "Käynnistetään mesh-client taajuudelle $mesh_mhz Mhz käyttäen laitetta $mesh_device"
    sudo modprobe batman-adv
    sudo killall wpa_supplicant 2>/dev/null
    sudo ip link set $mesh_device down
    sudo iw reg set $mesh_country
    sudo iwconfig $mesh_device txpower $mesh_txpower
    sudo ip link set mtu $mesh_mtu dev $mesh_device
    sleep 1
    sudo iw $mesh_device set type ibss
    sudo ip link set $mesh_device up
    sleep 2
    sudo iw $mesh_device ibss join mesh $mesh_mhz NOHT #HT20
    sudo batctl ra BATMAN_V
    #sudo batctl ra BATMAN_IV
    sudo batctl if add $mesh_device
    sudo ip link set bat0 up
    sudo batctl gw_mode client
    sudo ip link add name mesh-bridge type bridge
    sudo ip link set dev eth0 master mesh-bridge
    sudo ip link set dev bat0 master mesh-bridge
    sudo ip link set up dev eth0
    sudo ip link set up dev bat0
    sudo ip link set up dev mesh-bridge
    sudo ip addr add $mesh_ip/24 broadcast $mesh_broadcast dev mesh-bridge
    sudo ip route del default 2>/dev/null
    sudo ip route add default via $mesh_gateway
    #echo -e "Odottaa verkkoa\c"
    #while true; do
    #    if ping -c 1 -W 1 8.8.8.8 &> /dev/null
    #    then
    #        break
    #    fi
    #    echo -e ".\c"
    #    sleep 1
    #done
    #echo
    echo Valmis

elif [[ $1 == "down" ]];then
    if !(lsmod|grep batman_adv) >/dev/null;then
        echo "Ei ole käynnissä!"
        exit 1
    fi
    sudo ip link set $mesh_device down
    sudo ip addr flush dev $mesh_device
    sudo iw $mesh_device set type managed
    sudo rmmod batman-adv
    sudo ip link set mtu $mesh_mtu dev $mesh_device
    sudo ip link del mesh-bridge
else
    echo "käyttö:"
    echo "$0 {up|down}"
fi
