#!/bin/bash
#ARGUMENTIT:
#-u päivittää ilman dialogeja säilyttäen nykyiset ominaisuudet
#
#

##käydään komentorivi argumentit läpi:
for var in "$@"
do
    if [[ "$var" == "-u" ]];then update=1;fi
done

##tarkastetaan jo asennetut ominaisuudet:
k1=$(sudo dpkg-query -l |grep konttiraspi-mesh-client)
if [[ ${#k1} -gt 0 ]];then k1="on"; else k1="off"; fi
k2=$(sudo dpkg-query -l |grep konttiraspi-mesh-gateway)
if [[ ${#k2} -gt 0 ]];then k2="on"; else k2="off"; fi
k3=$(sudo dpkg-query -l |grep konttiraspi-sahkomittari-client)
if [[ ${#k3} -gt 0 ]];then k3="on"; else k3="off"; fi
k4=$(sudo dpkg-query -l |grep konttiraspi-sahkomittari-server)
if [[ ${#k4} -gt 0 ]];then k4="on"; else k4="off"; fi
k5=$(sudo dpkg-query -l |grep konttiraspi-kamera-client)
if [[ ${#k5} -gt 0 ]];then k5="on"; else k5="off"; fi
k6=$(sudo dpkg-query -l |grep konttiraspi-kamera-server)
if [[ ${#k6} -gt 0 ]];then k6="on"; else k6="off"; fi


if [[ $update != 1 ]];then
    cmd=(dialog --separate-output --checklist "valitse konttiraspi-system lisäksi asennettavat palvelut:" 22 76 16)
    options=(1 "konttiraspi-mesh-client" $k1
             2 "konttiraspi-mesh-gateway" $k2
             3 "konttiraspi-sahkomittari-client" $k3
             4 "konttiraspi-sahkomittari-server" $k4
             5 "konttiraspi-kamera-client" $k5
             6 "konttiraspi-kamera-server" $k6)
             
    choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
    okcancel=$?
    clear
    if [[ $okcancel != 0 ]]; then
        echo Peruuta
        exit
    fi
    for choice in $choices
    do
        case $choice in
            1)
                a1=1
                ;;
            2)
                a2=1
                ;;
            3)
                a3=1
                ;;
            4)
                a4=1
                ;;
            5)
                a5=1
                ;;
            6)
                a6=1
                ;;
        esac
    done
else #jos -u
    if [[ "$k1" == "on" ]]; then a1=1; fi
    if [[ "$k2" == "on" ]]; then a2=1; fi
    if [[ "$k3" == "on" ]]; then a3=1; fi
    if [[ "$k4" == "on" ]]; then a4=1; fi
    if [[ "$k5" == "on" ]]; then a5=1; fi
    if [[ "$k6" == "on" ]]; then a6=1; fi

fi

echo asennetaan konttiraspi-system
sudo apt install -y python3-configobj python3-pip git
sudo dpkg -i konttiraspi-system.deb
sudo raspi-config nonint do_wifi_country FI

if [[ $a1 == 1 ]]; then
    echo asennetaan konttiraspi-mesh-client
    sudo apt install -y batctl
    sudo pip3 install websocket-client
    sudo dpkg -i konttiraspi-mesh-client.deb
else
    if [[ "$k1" == "on" ]]; then
        echo poistetaan konttiraspi-mesh-client
        sudo dpkg -r konttiraspi-mesh-client
    fi
fi

if [[ $a2 == 1 ]]; then
    echo asennetaan konttiraspi-mesh-gateway
    sudo apt install -y  batctl libatlas-base-dev libopenjp2-7-dev libtiff5
    sudo pip3 install networkx matplotlib
    sudo dpkg -i konttiraspi-mesh-gateway.deb
    sudo chmod -R 777 /opt/konttiraspi/sahkomittari-server/data/
else
    if [[ "$k2" == "on" ]]; then
        echo poistetaan konttiraspi-mesh-gateway
        sudo dpkg -r konttiraspi-mesh-gateway
        nginx=1
    fi
fi


if [[ $a3 == 1 ]]; then
    echo asennetaan konttiraspi-sahkomittari-client
    sudo dpkg -i konttiraspi-sahkomittari-client.deb
    sudo apt -y install python3-serial
    sudo pip3 install websocket-client adafruit_dht
    #sudo pip3 install adafruit-circuitpython-dht websocket-client
else
    if [[ "$k3" == "on" ]]; then
        echo poistetaan konttiraspi-sahkomittari-client
        sudo dpkg -r konttiraspi-sahkomittari-client
    fi
fi

if [[ $a4 == 1 ]]; then
    echo asennetaan konttiraspi-sahkomittari-server
    sudo dpkg -i konttiraspi-sahkomittari-server.deb
    nginx=1
else
    if [[ "$k4" == "on" ]]; then
        echo poistetaan konttiraspi-sahkomittari-server
        sudo dpkg -r konttiraspi-sahkomittari-server
    fi
fi

if [[ $a5 == 1 ]]; then
    echo asennetaan konttiraspi-kamera-client
    sudo dpkg -i konttiraspi-kamera-client.deb
else
    if [[ "$k5" == "on" ]]; then
        echo poistetaan konttiraspi-kamera-client
        sudo dpkg -r konttiraspi-kamera-client
    fi
fi

if [[ $a6 == 1 ]]; then
    echo asennetaan konttiraspi-kamera-server
    sudo dpkg -i konttiraspi-kamera-server.deb
    nginx=1
else
    if [[ "$k6" == "on" ]]; then
        echo poistetaan konttiraspi-kamera-server
        sudo dpkg -r konttiraspi-kamera-server
    fi
fi



#-------------------------------------------------------------------------
### kirjoitetaan konffitiedosto ####
### varmistetaan onko koffi jo olemassa ###
if [ ! -f "/boot/asetukset.txt" ]; then
    dialog --defaultno --yesno "Asetustiedostoa ei löydy. Kirjoitetaanko mallitiedosto?" 22 76
    okcancel=$?
    clear
    if [[ "$okcancel" == "0" ]]; then
        sudo cp asetukset.txt /boot
        dialog --msgbox "Asetustiedosto /boot/asetukset.txt on luotu. Muista muokata se!" 22 76 && clear
    fi
fi

### nginx conffi jo tarpeellista ####
if [[ $nginx == 1 ]]; then
    sudo apt -y install -y nginx php7.3 php7.3-fpm php7.3-sqlite3 sqlite3
    sudo cp nginx.txt /etc/nginx/sites-available/default
fi


### reboot pyyntö ###
if [[ $update != 1 ]]; then
    dialog --msgbox "Asennus on valmis ja reboot on suositeltavaa tehdä nyt!" 22 76 && clear
fi
