#!/bin/bash
omamac=$(sudo batctl n|head -n1|cut -d " " -f5|cut -d "/" -f2)
omaip=$(ifconfig |grep bat0 -a1|tail -n1 |cut -d " " -f10)
echo tama laite $omamac $omaip
while read -r line
do
    nmac=$(echo $line |cut -d ' ' -f1)
    naika=$(echo $line |cut -d ' ' -f2|sed 's/.$//')
    nvoim=$(echo $line |cut -d ' ' -f4|sed 's/.$//')
    echo $nmac $naika $nvoim
done < <(sudo batctl n|tail -n +3)
